
MOUSEKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
UNICODEMAP_ENABLE = yes
SEND_STRING_ENABLE = yes
TAP_DANCE_ENABLE = yes
# CONVERT_TO = elite_pi
